version: "2"

services:
 #JupyterLab environment
 jupyter:
   build: .

   #password is 'secret'
   command: >-
     start.sh jupyter lab
     --NotebookApp.password=sha1:75c0514df417:e2b9f720d14cb9fd160b283a3d841d6f1de47115

   ports:
     - 8888:8888

   #Increase share memory size for DataLoader
   shm_size: 4G

   working_dir: /home/jovyan/work

   volumes:
     - .:/home/jovyan/work

   #match UID for login-user of host environment
   user: "1001"

   group_add:
     - users
